import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useAuthStore } from '@/store/auth';
import { useNotificationSettingsStore } from '@/store/notifications';
import { nativeStyles, nativeTheme } from '@/ui/nativeTheme';

export default function AlertsScreen() {
  const router = useRouter();
  const { user } = useAuthStore();
  const { inbox, loading, overspendAlertsEnabled, recurringAlertsEnabled, weeklySummaryAlertsEnabled, setOverspendAlertsEnabled, setRecurringAlertsEnabled, setWeeklySummaryAlertsEnabled, loadPreferences, syncPreferences, fetchInbox, markInboxItemRead, triggerScheduler } = useNotificationSettingsStore();
  const [refreshing, setRefreshing] = useState(false);

  useEffect(() => { if (user) { loadPreferences(user.id).catch(() => undefined); fetchInbox(user.id).catch(() => undefined); } }, [user, loadPreferences, fetchInbox]);
  const toggle = async (kind: 'overspend' | 'recurring' | 'weekly', value: boolean) => {
    if (kind === 'overspend') setOverspendAlertsEnabled(value); else if (kind === 'recurring') setRecurringAlertsEnabled(value); else setWeeklySummaryAlertsEnabled(value);
    if (user) { try { await syncPreferences(user.id); } catch { Alert.alert('Could not save preference', 'Your choice will stay on this device and we will try syncing again later.'); } }
  };
  const refresh = async () => { if (!user) return; setRefreshing(true); try { await triggerScheduler(user.id); await fetchInbox(user.id); } catch (error: any) { Alert.alert('Could not refresh alerts', error?.message || 'Try again soon.'); } finally { setRefreshing(false); } };
  const tone = (value: string) => value === 'warning' ? { bg: nativeTheme.warningSoft, icon: nativeTheme.warning, name: 'alert-circle-outline' as const } : value === 'success' ? { bg: nativeTheme.successSoft, icon: nativeTheme.success, name: 'checkmark-circle-outline' as const } : { bg: '#dff1eb', icon: nativeTheme.primary, name: 'information-circle-outline' as const };

  return <View style={nativeStyles.screen}><View style={nativeStyles.orbTop} /><View style={nativeStyles.orbBottom} /><ScrollView contentContainerStyle={[nativeStyles.content, styles.content]} showsVerticalScrollIndicator={false}>
    <Pressable style={styles.back} onPress={() => router.back()} hitSlop={4} accessibilityRole="button" accessibilityLabel="Back to dashboard"><Ionicons name="arrow-back" size={20} color="#ffffff" /><Text style={styles.backText}>Back to dashboard</Text></Pressable>
    <View style={nativeStyles.heroCard}><Text style={nativeStyles.heroEyebrow}>ALERT CENTER</Text><Text style={nativeStyles.heroTitle}>The signals that matter.</Text><Text style={nativeStyles.heroText}>Overspend warnings, upcoming recurring items, and weekly summaries stay together here.</Text></View>
    <View style={nativeStyles.card}><View style={styles.sectionHead}><View><Text style={nativeStyles.sectionEyebrow}>Preferences</Text><Text style={nativeStyles.sectionTitle}>What should we watch?</Text></View></View><Toggle title="Overspend warnings" body="Flag budget pace and category limits before they drift too far." value={overspendAlertsEnabled} onChange={(value) => toggle('overspend', value)} /><Toggle title="Recurring reminders" body="Keep upcoming rent, subscriptions, and income events visible." value={recurringAlertsEnabled} onChange={(value) => toggle('recurring', value)} /><Toggle title="Weekly summary" body="Get a compact review of the last seven days of spending." value={weeklySummaryAlertsEnabled} onChange={(value) => toggle('weekly', value)} /></View>
    <View style={nativeStyles.card}><View style={styles.sectionHead}><View><Text style={nativeStyles.sectionEyebrow}>Inbox</Text><Text style={nativeStyles.sectionTitle}>{inbox.length ? `${inbox.length} unread alert${inbox.length === 1 ? '' : 's'}` : 'All caught up'}</Text></View><Pressable style={styles.refresh} onPress={refresh} disabled={refreshing} hitSlop={4} accessibilityRole="button" accessibilityState={{ busy: refreshing, disabled: refreshing }} accessibilityLabel="Refresh alerts">{refreshing ? <ActivityIndicator size="small" color={nativeTheme.primary} /> : <Ionicons name="refresh" size={17} color={nativeTheme.primary} />}</Pressable></View>
      {loading && inbox.length === 0 ? <ActivityIndicator color={nativeTheme.primary} /> : inbox.length === 0 ? <View style={styles.empty}><Ionicons name="sparkles-outline" size={27} color={nativeTheme.primary} /><Text style={styles.emptyTitle}>Your budget is quiet.</Text><Text style={styles.emptyText}>New warnings and summaries will show here when there is something useful to act on.</Text></View> : inbox.map((item) => { const visual = tone(item.tone); return <Pressable key={item.id} style={styles.alertRow} onPress={() => markInboxItemRead(item.id)}><View style={[styles.alertIcon, { backgroundColor: visual.bg }]}><Ionicons name={visual.name} size={22} color={visual.icon} /></View><View style={styles.alertCopy}><Text style={styles.alertTitle}>{item.title}</Text><Text style={styles.alertBody}>{item.body}</Text><Text style={styles.dismiss}>Tap to mark as read</Text></View></Pressable>; })}
    </View>
  </ScrollView></View>;
}

function Toggle({ title, body, value, onChange }: { title: string; body: string; value: boolean; onChange: (value: boolean) => void }) { return <View style={styles.toggle}><View style={styles.toggleCopy}><Text style={styles.toggleTitle}>{title}</Text><Text style={styles.toggleBody}>{body}</Text></View><Switch value={value} onValueChange={onChange} trackColor={{ false: '#d6e5e0', true: '#83b9aa' }} thumbColor={value ? nativeTheme.primary : '#ffffff'} /></View>; }

const styles = StyleSheet.create({ content: { paddingBottom: 50 }, back: { alignSelf: 'flex-start', minHeight: 44, borderRadius: 14, paddingHorizontal: 13, backgroundColor: nativeTheme.navy, flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 14 }, backText: { color: '#ffffff', fontSize: 12, fontWeight: '900' }, sectionHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }, refresh: { width: 44, height: 44, borderRadius: 14, backgroundColor: nativeTheme.surfaceMuted, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: nativeTheme.border }, toggle: { flexDirection: 'row', gap: 12, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: nativeTheme.border, alignItems: 'center' }, toggleCopy: { flex: 1 }, toggleTitle: { color: nativeTheme.ink, fontSize: 14, fontWeight: '900' }, toggleBody: { color: nativeTheme.muted, fontSize: 12, lineHeight: 18, marginTop: 4 }, empty: { alignItems: 'center', paddingVertical: 18 }, emptyTitle: { color: nativeTheme.ink, fontSize: 15, fontWeight: '900', marginTop: 8 }, emptyText: { color: nativeTheme.muted, fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 5 }, alertRow: { flexDirection: 'row', gap: 11, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: nativeTheme.border }, alertIcon: { width: 43, height: 43, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, alertCopy: { flex: 1 }, alertTitle: { color: nativeTheme.ink, fontSize: 14, fontWeight: '900' }, alertBody: { color: nativeTheme.muted, fontSize: 12, lineHeight: 18, marginTop: 4 }, dismiss: { color: nativeTheme.primary, fontSize: 11, fontWeight: '900', marginTop: 7 }, });
