import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useAuthStore } from '@/store/auth';
import { useBudgetStore } from '@/store/budget';
import { formatMoney, nativeStyles, nativeTheme } from '@/ui/nativeTheme';

const EXPENSE_CATEGORIES = ['Food', 'Transport', 'Entertainment', 'Utilities', 'Other'];
const INCOME_CATEGORIES = ['Salary', 'Business', 'Investment', 'Gift', 'Other'];

export default function RoutinesScreen() {
  const router = useRouter(); const { user } = useAuthStore(); const { budget, recurringTransactions, loading, fetchRecurringTransactions, addRecurringTransaction, deleteRecurringTransaction } = useBudgetStore();
  const [open, setOpen] = useState(false); const [type, setType] = useState<'expense' | 'income'>('expense'); const [frequency, setFrequency] = useState<'monthly' | 'weekly' | 'daily'>('monthly'); const [amount, setAmount] = useState(''); const [category, setCategory] = useState('Food'); const [date, setDate] = useState(''); const [note, setNote] = useState('');
  useEffect(() => { if (user) fetchRecurringTransactions(user.id); }, [user, fetchRecurringTransactions]);
  if (!budget) return null;
  const categories = type === 'expense' ? EXPENSE_CATEGORIES : INCOME_CATEGORIES;
  const save = async () => { const value = Number(amount); if (!user || !Number.isFinite(value) || value <= 0 || !/^\d{4}-\d{2}-\d{2}$/.test(date)) return Alert.alert('Check this routine', 'Add a valid amount and first date in YYYY-MM-DD format.'); try { await addRecurringTransaction(user.id, value, category, type, frequency, date, note || undefined); setAmount(''); setDate(''); setNote(''); setOpen(false); } catch (error: any) { Alert.alert('Could not save routine', error?.message || 'Try again.'); } };
  const remove = (id: string) => Alert.alert('Remove routine?', 'Future automatic entries from this schedule will stop.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: () => deleteRecurringTransaction(id).catch((error) => Alert.alert('Could not remove routine', error?.message || 'Try again.')) }]);
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : 'height'} style={nativeStyles.screen}><View style={nativeStyles.orbTop} /><View style={nativeStyles.orbBottom} /><ScrollView contentContainerStyle={[nativeStyles.content, styles.content]} showsVerticalScrollIndicator={false}>
    <Pressable style={styles.back} onPress={() => router.back()}><Ionicons name="arrow-back" size={20} color="#ffffff" /><Text style={styles.backText}>Back to settings</Text></Pressable>
    <View style={nativeStyles.heroCard}><Text style={nativeStyles.heroEyebrow}>RECURRING ROUTINES</Text><Text style={nativeStyles.heroTitle}>Put repeats on autopilot.</Text><Text style={nativeStyles.heroText}>Set a bill, subscription, or regular income once. Budget It adds it on schedule and keeps you aware of what is ahead.</Text></View>
    <View style={nativeStyles.card}><View style={styles.heading}><View><Text style={nativeStyles.sectionEyebrow}>Scheduled entries</Text><Text style={nativeStyles.sectionTitle}>{recurringTransactions.length ? `${recurringTransactions.length} routine${recurringTransactions.length === 1 ? '' : 's'}` : 'Nothing scheduled yet'}</Text></View><Pressable style={styles.add} onPress={() => setOpen(!open)}><Ionicons name="add" size={16} color="#ffffff" /><Text style={styles.addText}>Routine</Text></Pressable></View>
      {recurringTransactions.map((item) => <View key={item.id} style={styles.routine}><View style={[styles.routineIcon, { backgroundColor: item.type === 'income' ? nativeTheme.successSoft : nativeTheme.warningSoft }]}><Ionicons name={item.type === 'income' ? 'trending-up' : 'repeat'} size={20} color={item.type === 'income' ? nativeTheme.success : nativeTheme.warning} /></View><View style={styles.routineCopy}><Text style={styles.routineTitle}>{item.category}</Text><Text style={styles.routineMeta}>{item.frequency} from {item.next_date}{item.note ? ` - ${item.note}` : ''}</Text></View><View style={styles.routineRight}><Text style={[styles.routineAmount, { color: item.type === 'income' ? nativeTheme.success : nativeTheme.ink }]}>{item.type === 'income' ? '+' : '-'}{formatMoney(item.amount, budget.currency)}</Text><Pressable onPress={() => remove(item.id)}><Text style={styles.remove}>Remove</Text></Pressable></View></View>)}
      {!recurringTransactions.length && !open ? <Text style={styles.empty}>Add the things that reliably repeat so your forecast and alerts can do more of the thinking for you.</Text> : null}
      {open ? <View style={styles.form}><Text style={nativeStyles.label}>Type</Text><View style={styles.row}>{(['expense', 'income'] as const).map((item) => <Pressable key={item} style={[styles.choice, type === item && styles.choiceActive]} onPress={() => { setType(item); setCategory(item === 'expense' ? 'Food' : 'Salary'); }}><Text style={[styles.choiceText, type === item && styles.choiceTextActive]}>{item}</Text></Pressable>)}</View><Text style={nativeStyles.label}>Frequency</Text><View style={styles.row}>{(['monthly', 'weekly', 'daily'] as const).map((item) => <Pressable key={item} style={[styles.choice, frequency === item && styles.choiceActive]} onPress={() => setFrequency(item)}><Text style={[styles.choiceText, frequency === item && styles.choiceTextActive]}>{item}</Text></Pressable>)}</View><Text style={nativeStyles.label}>Category</Text><View style={styles.categoryRow}>{categories.map((item) => <Pressable key={item} style={[nativeStyles.chip, category === item && nativeStyles.chipActive]} onPress={() => setCategory(item)}><Text style={[nativeStyles.chipText, category === item && nativeStyles.chipTextActive]}>{item}</Text></Pressable>)}</View><Field value={amount} onChangeText={setAmount} placeholder="Amount" numeric /><Field value={date} onChangeText={setDate} placeholder="First date (YYYY-MM-DD)" /><Field value={note} onChangeText={setNote} placeholder="Note (optional)" /><Pressable style={nativeStyles.primaryButton} onPress={save} disabled={loading}>{loading ? <ActivityIndicator color="#ffffff" /> : <Text style={nativeStyles.primaryButtonText}>Save routine</Text>}</Pressable></View> : null}
    </View>
  </ScrollView></KeyboardAvoidingView>;
}
function Field({ value, onChangeText, placeholder, numeric }: { value: string; onChangeText: (value: string) => void; placeholder: string; numeric?: boolean }) { return <View style={styles.field}><TextInput style={nativeStyles.input} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#8ca19e" keyboardType={numeric ? 'decimal-pad' : 'default'} /></View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 50 }, back: { alignSelf: 'flex-start', minHeight: 42, borderRadius: 14, paddingHorizontal: 13, backgroundColor: nativeTheme.navy, flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 14 }, backText: { color: '#ffffff', fontSize: 12, fontWeight: '900' }, heading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }, add: { minHeight: 35, borderRadius: 12, paddingHorizontal: 10, backgroundColor: nativeTheme.primary, flexDirection: 'row', alignItems: 'center', gap: 4 }, addText: { color: '#ffffff', fontSize: 11, fontWeight: '900' }, routine: { flexDirection: 'row', gap: 10, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: nativeTheme.border }, routineIcon: { width: 41, height: 41, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, routineCopy: { flex: 1 }, routineTitle: { color: nativeTheme.ink, fontSize: 14, fontWeight: '900' }, routineMeta: { color: nativeTheme.muted, fontSize: 11, lineHeight: 16, marginTop: 4 }, routineRight: { alignItems: 'flex-end' }, routineAmount: { fontSize: 12, fontWeight: '900' }, remove: { color: nativeTheme.danger, fontSize: 11, fontWeight: '900', marginTop: 7 }, empty: { color: nativeTheme.muted, fontSize: 13, lineHeight: 20 }, form: { gap: 10, paddingTop: 16, marginTop: 14, borderTopWidth: 1, borderTopColor: nativeTheme.border }, row: { flexDirection: 'row', gap: 8, marginBottom: 3 }, choice: { flex: 1, minHeight: 40, borderRadius: 13, backgroundColor: nativeTheme.surfaceMuted, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: nativeTheme.border }, choiceActive: { backgroundColor: nativeTheme.navy, borderColor: nativeTheme.navy }, choiceText: { color: nativeTheme.muted, fontSize: 12, fontWeight: '900', textTransform: 'capitalize' }, choiceTextActive: { color: '#ffffff' }, categoryRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 3 }, field: { minHeight: 50, borderRadius: 15, backgroundColor: nativeTheme.surfaceMuted, borderWidth: 1, borderColor: nativeTheme.border, paddingHorizontal: 13 }, });
