import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Platform } from 'react-native';

export type AppLanguage = 'en' | 'sw';

type TranslationLeaf = string;
type TranslationTree = {
  [key: string]: TranslationLeaf | TranslationTree;
};

interface LanguageState {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
}

type TemplateValues = Record<string, string | number>;

const localStorageAdapter = {
  getItem: (name: string) => {
    if (typeof window === 'undefined') return null;
    return window.localStorage.getItem(name);
  },
  setItem: (name: string, value: string) => {
    if (typeof window === 'undefined') return;
    window.localStorage.setItem(name, value);
  },
  removeItem: (name: string) => {
    if (typeof window === 'undefined') return;
    window.localStorage.removeItem(name);
  },
};

const languageStorage = createJSONStorage(() => (
  Platform.OS === 'web' ? localStorageAdapter : AsyncStorage
));

export const translations = {
  en: {
    common: {
      appName: 'Budget It',
      back: 'Back',
      save: 'Save',
      cancel: 'Cancel',
      loading: 'Loading...',
      settings: 'Settings',
      help: 'Help',
      guides: 'Guides',
      questionMark: '?',
      english: 'English',
      swahili: 'Swahili',
    },
    auth: {
      heroBadge: 'Smarter personal finance, built for everyday use',
      heroTitle: 'Budget with clarity, not guesswork.',
      heroSubtitle:
        'Track spending, monitor your balance, and stay on top of your goals with a cleaner, faster budgeting flow designed to work well on both desktop and mobile.',
      featureTracking: 'Clear daily and monthly tracking',
      featureQuickLogging: 'Quick transaction logging',
      featureResponsive: 'Mobile-friendly responsive web app',
      featureSecure: 'Secure account-based access',
      metricVisibility: 'budget visibility',
      metricOneView: 'for balances and trends',
      metricSetup: 'setup and onboarding',
      tagLine: 'Track your spending, save smarter',
      welcomeBack: 'Welcome back',
      welcomeSubtitle: 'Sign in to continue tracking your budget, balances, and recent spending.',
      signIn: 'Sign In',
      signingIn: 'Signing in...',
      createAccount: 'Create your account',
      signUp: 'Sign up free',
      signingUp: 'Creating account...',
      noAccount: "Don't have an account?",
      haveAccount: 'Already have an account?',
      emailPlaceholder: 'Email address',
      passwordPlaceholder: 'Password',
      confirmPasswordPlaceholder: 'Confirm password',
      fillAllFields: 'Please fill in all fields',
      passwordTooShort: 'Password must be at least 6 characters',
      passwordsDoNotMatch: 'Passwords do not match',
      signupSuccess: 'Account created! Check your email to verify, then sign in.',
      loginError: 'Login failed. Check your credentials.',
      signupError: 'Signup failed',
    },
    dashboard: {
      overview: 'Overview',
      budgetAtGlance: 'Your budget at a glance',
      daysLeftInCycle: 'days left in cycle',
      allAccounts: 'All accounts',
      bankAccount: 'Bank account',
      quickAddFood: 'Add food expense',
      quickLogIncome: 'Log income',
      quickMoveMoney: 'Move money',
      history: 'History',
      analytics: 'Analytics',
      helpTitle: 'Guides',
      recentTransactions: 'Recent Transactions',
      viewAll: 'View all',
      noTransactions: 'No transactions yet',
      addFirstTransaction: 'Add your first transaction',
      alertsAndSummaries: 'Alerts and summaries',
      notifications: 'Notifications',
      backOnlineSyncing: 'Back online! Syncing data...',
      syncComplete: 'Sync complete!',
      preparingDashboard: 'Preparing dashboard...',
      loadingBudgetTitle: 'Loading your budget at a glance',
      loadingBudgetSubtitle: "Your account is signed in. We're finishing your dashboard data now.",
      welcomeTitle: 'Welcome to Budget It!',
      welcomeSubtitle: 'Set up your daily and monthly spending targets to start tracking your finances.',
      setupBudgetCta: 'Set Up My Budget',
      accountBalance: 'Account Balance',
      viewCombinedBalance: 'Viewing your combined balance across {count} account{suffix}.',
      viewSingleBalance: 'Viewing the current balance for {label}.',
      trackedAccounts: 'Tracked Accounts',
      bankAndEnvelopesAvailable: 'Bank + envelopes available',
      transactionsLoggedTitle: 'Transactions Logged',
      acrossCurrentCycle: 'Across your current budget cycle',
      dailyTargetTitle: 'Daily Target',
      monthlyTargetTitle: 'Monthly Target',
      selectedAccountTitle: 'Selected Account',
      todayTitle: 'Today',
      monthToDateTitle: 'Month to date',
      projectionTitle: 'Projection',
      todaysSpending: "Today's Spending",
      projectedMonthEnd: 'Projected Month End',
      dailyBudgetTitle: 'Daily Budget',
      monthlyBudgetTitle: 'Monthly Budget',
      overLimitShort: 'over limit',
      remainingToday: 'remaining today',
      remainingThisMonth: 'remaining this month',
      insightsTitle: 'Insights',
      spendingPaceTitle: 'Spending pace',
      averageDailySpend: 'Average daily spend',
      safeDailySpend: 'Safe daily spend',
      pacingOver: 'At this pace, you may exceed your monthly budget by {amount}.',
      pacingUnder: 'You are currently pacing {amount} under your monthly target.',
      keepDailySpend: 'Keep daily spending near {amount} for the remaining {days} day{suffix} to stay on track.',
      weeklySummaryTitle: 'Weekly summary',
      weeklySummaryBody: 'You have spent {amount} over the last 7 days, averaging {average} per day.',
      categoryWatchTitle: 'Category Watch',
      trackedLimitsTitle: 'Tracked limits',
      addCategoryLimitsHint: 'Add category limits in Settings to see progress bars and early warnings here.',
      overLimitLabel: 'Over limit',
      almostThereLabel: 'Almost there',
      onTrackLabel: 'On track',
      overAmount: '{amount} over',
      remainingAmount: '{amount} remaining',
      rolledInAmount: '{amount} rolled in',
      goalsTitle: 'Goals',
      savingsProgressTitle: 'Savings progress',
      manage: 'Manage',
      savingsGoalsHint: 'Add savings goals in Settings to track progress toward things like an emergency fund, travel, or school fees.',
      completePercent: '{percent}% complete',
      goalProgressLine: '{current} of {target} - {remainingLabel} - {daysLabel}',
      toGoAmount: '{amount} to go',
      goalReached: 'Goal reached',
      daysLeftLabel: '{count} day{suffix} left',
      targetDateReached: 'Target date reached',
      enableBrowserAlertsTitle: 'Enable browser alerts',
      enableBrowserAlertsBody: 'Turn on browser notifications for overspend warnings and upcoming recurring items when you have the app open in your browser.',
      notificationsBlocked: 'Notifications blocked in browser settings',
      enableAlerts: 'Enable alerts',
      notificationsEmpty: 'You are all caught up. Weekly summaries, overspend warnings, and upcoming recurring items will appear here.',
      timeLast7Days: 'Last 7 days',
      timeCurrentCycle: 'Current cycle',
      timeAllTime: 'All time',
      allCategories: 'All categories',
      editHint: 'Use Edit for quick changes, or double-click a row if you prefer keyboard-style editing.',
      noTransactionsMatch: 'No transactions match this dashboard view yet.',
      edit: 'Edit',
      editing: 'Editing',
      delete: 'Delete',
      deleting: 'Deleting...',
      transferIn: 'Transfer in',
      transferOut: 'Transfer out',
      editingSelectedTransaction: 'Editing selected transaction',
      saveChanges: 'Save changes',
      saving: 'Saving...',
      amountPlaceholder: 'Amount',
      categoryPlaceholder: 'Category',
      merchantPlaceholder: 'Merchant',
      notePlaceholder: 'Note',
      transactionUpdated: 'Transaction updated',
      transactionDeleted: 'Transaction deleted',
      saveTransactionError: 'Enter a valid amount before saving.',
      updateTransactionError: 'Could not update this transaction.',
      deleteTransactionConfirm: 'Delete this transaction from your dashboard list?',
      deleteTransactionError: 'Could not delete this transaction.',
      browserAlertsEnabled: 'Browser alerts enabled',
      monthlyOverspendWarning: 'Monthly overspend warning',
      monthlyOverspendBody: 'At the current pace, you are trending {amount} over your cycle budget.',
      categoryCloseTitle: '{category} is getting close',
      categoryOverBody: 'You have already gone {amount} over your {category} limit.',
      categoryRemainingBody: '{amount} remains in {category} for this cycle.',
      upcomingRecurringTitle: 'Upcoming recurring {type}',
      upcomingRecurringBody: '{category} is due in {days} day{suffix} on {date}.',
      weeklySummaryNotificationBody: 'Last 7 days: {spent} spent. Safe daily spend for the rest of this cycle is {safe}.',
    },
    settings: {
      preferences: 'Preferences',
      settingsTitle: 'Settings',
      appearance: 'Appearance',
      appearanceSubtitle: 'Choose how the web app looks. Your preference is saved on this device.',
      lightMode: 'Light mode',
      darkMode: 'Dark mode',
      toggleTo: 'Toggle to',
      languageAndHelp: 'Language & help',
      languageSubtitle: 'Choose the language you want to use in the app and open quick guides when you need a refresher.',
      appLanguage: 'App language',
      openQuickGuides: 'Open quick guides',
      quickGuidesSubtitle: 'Learn the basics, transfers, recurring entries, and budget-cycle tips in one place.',
      budgetTargets: 'Budget Targets',
      account: 'Account',
      signedInAs: 'Signed in as',
      signOut: 'Sign Out',
      confirmSignOut: 'Confirm Sign Out',
      alertsAndReminders: 'Alerts & reminders',
      alertsSubtitle: 'Choose which alerts you want to see. Installed web apps on phones and desktop browsers work best for these notifications.',
      browserInstalledAlerts: 'Browser or installed-app alerts',
      browserAlertsEnabledBody: 'Enabled for this browser. Budget It can send reminder popups while the app is available.',
      browserAlertsDisabledBody: 'Turn this on to allow reminder popups in your browser or installed web app.',
      browserAlertsUnsupportedBody: 'This browser does not expose the notification API, so alerts will stay inside the app.',
      overspendWarnings: 'Overspend and category warnings',
      overspendWarningsBody: 'Get warned when your cycle pace or tracked categories start drifting off target.',
      recurringReminders: 'Upcoming recurring reminders',
      recurringRemindersBody: 'Show reminders when rent, subscriptions, salary, or other recurring items are due soon.',
      weeklySummaryUpdates: 'Weekly summary updates',
      weeklySummaryUpdatesBody: 'Keep a weekly spending summary in the dashboard and allow it to appear in alerts.',
      on: 'On',
      off: 'Off',
      allowBrowserNotifications: 'Allow browser notifications',
      phoneFriendlyTip: 'Phone-friendly tip',
      phoneFriendlyTipBody: 'If you add Budget It to your home screen, notification prompts and reminder popups usually feel more app-like than using a browser tab alone.',
    },
    guides: {
      eyebrow: 'Quick Guides',
      title: 'How to use Budget It',
      subtitle:
        'Short walkthroughs for the most important parts of the app, so you can get unstuck fast without leaving your budget flow.',
      cardGettingStarted: 'Getting started',
      cardGettingStartedBody:
        'Set your daily target, monthly target, currency, and cycle start day in Settings first. Then add your first transaction from the dashboard.',
      cardTransfers: 'Moving money',
      cardTransfersBody:
        'Use Move money when cash shifts between your bank account and envelopes. Transfers change balances without counting as spending.',
      cardRecurring: 'Recurring transactions',
      cardRecurringBody:
        'Use recurring transactions for salary, rent, subscriptions, and bills. The dashboard alerts area will show items coming up soon.',
      cardInsights: 'Insights and limits',
      cardInsightsBody:
        'Category limits power warnings, while the dashboard and analytics screens compare your spending pace against the current budget cycle.',
      cardTags: 'Merchants and tags',
      cardTagsBody:
        'Add a merchant and a few tags when logging transactions. This helps the app suggest matches and makes future insights more useful.',
      tipTitle: 'Pro tip',
      tipBody:
        'If your budget resets on a day other than the 1st, update the cycle start day in Settings so all analytics follow your real routine.',
      needAnythingElse: 'Need anything else?',
      needAnythingElseBody:
        'You can return here anytime from the question-mark button in the top navigation or the Language & help card in Settings.',
    },
    mobile: {
      nav: { dashboard: 'Dashboard', add: 'Add', history: 'History', insights: 'Insights', settings: 'Settings' },
      dashboard: {
        loading: 'Loading your money dashboard...',
        loadError: 'Could not load your budget',
        setupTitle: 'Set up your money space',
        setupBody: 'A quick three-step setup gives Budget It the context it needs to guide your spending.',
        setupStepOne: 'Choose your daily and monthly targets',
        setupStepTwo: 'Pick your currency and cycle start day',
        setupStepThree: 'Add your first expense when setup is complete',
        openSetup: 'Start setup',
        tryAgain: 'Try again',
        offline: 'You are offline. Showing your last saved budget.',
        title: 'Your budget pulse',
        overPace: 'At this pace, you may go over by {amount}.',
        underPace: 'You are pacing {amount} under target.',
        syncing: 'Syncing your budget',
        syncPulse: 'Sync pulse',
        refreshing: 'Refreshing data',
        updatedAt: 'Updated {time}',
        tapToRefresh: 'Tap to refresh',
        available: 'Available',
        safeToday: 'Safe today',
        addExpense: 'Add expense',
        logIncome: 'Log income',
        moveMoney: 'Move money',
        today: 'Today',
        cycle: 'Cycle',
        dailyTarget: '{percent}% of daily target',
        currentCycle: 'Current cycle',
        insights: 'Insights',
        stayOnTrack: 'Stay on track',
        slowPace: 'Slow the pace a little',
        roomToBreathe: 'You have room to breathe',
        safeSpend: 'Keep spending near {amount} per day for the next {days} days to finish this cycle cleanly.',
        categoryWatch: 'Category watch',
        trackedLimits: 'Tracked limits',
        manage: 'Manage',
        categoryHint: 'Add category limits in Settings to see progress and early warnings here.',
        over: 'Over',
        almostThere: 'Almost there',
        onTrack: 'On track',
        spentOfLeft: '{spent} of {limit} - {remaining} left',
        recentActivity: 'Recent activity',
        latestTransactions: 'Latest transactions',
        viewAll: 'View all',
        noTransactions: 'No transactions yet. Add one and the dashboard starts lighting up.',
      },
      transactions: {
        loading: 'Loading transactions...',
        offline: 'Offline mode: showing your last saved transactions.',
        eyebrow: 'Money trail',
        title: 'Transactions',
        subtitle: 'Review spending, income, transfers, merchants, and notes in one clean feed.',
        expenses: 'Expenses',
        incomeEntries: 'Income entries',
        transfers: 'Transfers',
        searchPlaceholder: 'Search merchant, category, note, or tag',
        allTime: 'All time',
        lastSevenDays: 'Last 7 days',
        thisMonth: 'This month',
        all: 'All',
        income: 'Income',
        noResults: 'No transactions match these filters.',
        noResultsBody: 'Try clearing a filter or searching for something else.',
        loadError: 'Could not load transactions',
        empty: 'No transactions yet',
        emptyBody: 'Add your first expense or income entry and it will appear here with merchant and tag details.',
        retry: 'Try again',
        recurring: 'Recurring',
        actions: 'Transaction actions',
        deleteBody: 'This will remove the transaction and update balances.',
        deleteFailed: 'Could not delete this transaction. Please try again.',
        edit: 'Edit',
        delete: 'Delete',
        cancel: 'Cancel',
        transfer: 'Transfer',
      },
      transactionForm: {
        budgetFirst: 'Budget first',
        budgetFirstBody: 'Set your targets in Settings, then come back to log spending.',
        eyebrow: 'Quick capture',
        title: 'Add a money move',
        subtitle: 'Log the amount, merchant, tags, and category while the detail is still fresh.',
        type: 'Type', expense: 'Expense', income: 'Income', moneySpace: 'Money space',
        moneySpaceHint: 'Choose where this money should be recorded.', bankBalance: 'Bank balance', available: 'available',
        amount: 'Amount', category: 'Category', details: 'Details', merchantPlaceholder: 'Merchant, person, or source',
        recentMerchants: 'Recent merchants', tagsPlaceholder: 'Tags separated by commas', datePlaceholder: 'YYYY-MM-DD', notePlaceholder: 'Add a note...',
        saveExpense: 'Save expense', saveIncome: 'Save income', saving: 'Saving...',
        amountNeeded: 'Amount needed', validAmount: 'Please enter a valid amount.', budgetNotReady: 'Budget not ready', setupBudget: 'Please set up your budget first.',
        saved: 'Saved', incomeLogged: 'Income logged.', expenseAdded: 'Expense added.', savedOffline: 'Saved on this device. It will sync automatically when you are back online.',
        saveFailed: 'Could not save',
      },
    },
  },
  sw: {
    common: {
      appName: 'Budget It',
      back: 'Rudi',
      save: 'Hifadhi',
      cancel: 'Ghairi',
      loading: 'Inapakia...',
      settings: 'Mipangilio',
      help: 'Msaada',
      guides: 'Mwongozo',
      questionMark: '?',
      english: 'Kiingereza',
      swahili: 'Kiswahili',
    },
    auth: {
      heroBadge: 'Fedha binafsi zenye akili, kwa matumizi ya kila siku',
      heroTitle: 'Panga bajeti kwa uwazi, si kubahatisha.',
      heroSubtitle:
        'Fuatilia matumizi, angalia salio lako, na simamia malengo yako kwa mfumo safi na wa haraka unaofanya kazi vizuri kwenye kompyuta na simu.',
      featureTracking: 'Ufuatiliaji wazi wa kila siku na kila mwezi',
      featureQuickLogging: 'Kuingiza miamala kwa haraka',
      featureResponsive: 'Programu ya wavuti rafiki kwa simu',
      featureSecure: 'Upatikanaji salama wa akaunti',
      metricVisibility: 'muonekano wa bajeti',
      metricOneView: 'kwa salio na mwenendo',
      metricSetup: 'usanidi na kuanza kutumia',
      tagLine: 'Fuatilia matumizi yako, okoa kwa busara',
      welcomeBack: 'Karibu tena',
      welcomeSubtitle: 'Ingia uendelee kufuatilia bajeti, salio, na matumizi yako ya hivi karibuni.',
      signIn: 'Ingia',
      signingIn: 'Inaingia...',
      createAccount: 'Fungua akaunti yako',
      signUp: 'Jisajili bure',
      signingUp: 'Inatengeneza akaunti...',
      noAccount: 'Huna akaunti?',
      haveAccount: 'Tayari una akaunti?',
      emailPlaceholder: 'Anwani ya barua pepe',
      passwordPlaceholder: 'Nenosiri',
      confirmPasswordPlaceholder: 'Thibitisha nenosiri',
      fillAllFields: 'Tafadhali jaza sehemu zote',
      passwordTooShort: 'Nenosiri lazima liwe angalau herufi 6',
      passwordsDoNotMatch: 'Nenosiri halifanani',
      signupSuccess: 'Akaunti imefunguliwa! Angalia barua pepe yako kuthibitisha, kisha ingia.',
      loginError: 'Kuingia kumeshindikana. Hakikisha taarifa zako ni sahihi.',
      signupError: 'Usajili umeshindikana',
    },
    dashboard: {
      overview: 'Muhtasari',
      budgetAtGlance: 'Muonekano wa haraka wa bajeti yako',
      daysLeftInCycle: 'siku zilizobaki kwenye mzunguko',
      allAccounts: 'Akaunti zote',
      bankAccount: 'Akaunti ya benki',
      quickAddFood: 'Ongeza matumizi ya chakula',
      quickLogIncome: 'Weka mapato',
      quickMoveMoney: 'Hamisha fedha',
      history: 'Historia',
      analytics: 'Takwimu',
      helpTitle: 'Mwongozo',
      recentTransactions: 'Miamala ya hivi karibuni',
      viewAll: 'Tazama yote',
      noTransactions: 'Hakuna miamala bado',
      addFirstTransaction: 'Ongeza muamala wako wa kwanza',
      alertsAndSummaries: 'Tahadhari na muhtasari',
      notifications: 'Arifa',
      backOnlineSyncing: 'Mtandao umerejea! Inasawazisha data...',
      syncComplete: 'Usawazishaji umekamilika!',
      preparingDashboard: 'Inaandaa dashboard...',
      loadingBudgetTitle: 'Inapakia muhtasari wa bajeti yako',
      loadingBudgetSubtitle: 'Akaunti yako imeingia. Tunakamilisha data ya dashboard yako sasa.',
      welcomeTitle: 'Karibu Budget It!',
      welcomeSubtitle: 'Weka malengo yako ya matumizi ya kila siku na kila mwezi ili uanze kufuatilia fedha zako.',
      setupBudgetCta: 'Anza kuweka bajeti',
      accountBalance: 'Salio la akaunti',
      viewCombinedBalance: 'Unaona salio la pamoja la akaunti {count}{suffix}.',
      viewSingleBalance: 'Unaona salio la sasa la {label}.',
      trackedAccounts: 'Akaunti zinazofuatiliwa',
      bankAndEnvelopesAvailable: 'Benki na envelope zilizopo',
      transactionsLoggedTitle: 'Miamala iliyoingizwa',
      acrossCurrentCycle: 'Katika mzunguko wa sasa wa bajeti',
      dailyTargetTitle: 'Lengo la kila siku',
      monthlyTargetTitle: 'Lengo la kila mwezi',
      selectedAccountTitle: 'Akaunti iliyochaguliwa',
      todayTitle: 'Leo',
      monthToDateTitle: 'Mwezi hadi sasa',
      projectionTitle: 'Makadirio',
      todaysSpending: 'Matumizi ya leo',
      projectedMonthEnd: 'Makadirio ya mwisho wa mwezi',
      dailyBudgetTitle: 'Bajeti ya kila siku',
      monthlyBudgetTitle: 'Bajeti ya kila mwezi',
      overLimitShort: 'imezidi kiwango',
      remainingToday: 'imebaki leo',
      remainingThisMonth: 'imebaki mwezi huu',
      insightsTitle: 'Taarifa',
      spendingPaceTitle: 'Kasi ya matumizi',
      averageDailySpend: 'Wastani wa matumizi ya siku',
      safeDailySpend: 'Matumizi salama ya siku',
      pacingOver: 'Kwa mwendo huu, unaweza kuzidi bajeti ya mwezi kwa {amount}.',
      pacingUnder: 'Kwa sasa uko chini ya lengo la mwezi kwa {amount}.',
      keepDailySpend: 'Weka matumizi karibu na {amount} kwa siku {days} zilizobaki ili ubaki kwenye mstari.',
      weeklySummaryTitle: 'Muhtasari wa wiki',
      weeklySummaryBody: 'Umetumia {amount} katika siku 7 zilizopita, wastani wa {average} kwa siku.',
      categoryWatchTitle: 'Ufuatiliaji wa category',
      trackedLimitsTitle: 'Mipaka inayofuatiliwa',
      addCategoryLimitsHint: 'Ongeza mipaka ya category kwenye Mipangilio ili kuona progress na tahadhari mapema hapa.',
      overLimitLabel: 'Imezidi kiwango',
      almostThereLabel: 'Imekaribia',
      onTrackLabel: 'Ipo sawa',
      overAmount: '{amount} juu ya kiwango',
      remainingAmount: '{amount} imebaki',
      rolledInAmount: '{amount} imeletwa kutoka mzunguko uliopita',
      goalsTitle: 'Malengo',
      savingsProgressTitle: 'Maendeleo ya akiba',
      manage: 'Simamia',
      savingsGoalsHint: 'Ongeza malengo ya akiba kwenye Mipangilio kufuatilia vitu kama emergency fund, safari, au ada ya shule.',
      completePercent: '{percent}% imekamilika',
      goalProgressLine: '{current} kati ya {target} - {remainingLabel} - {daysLabel}',
      toGoAmount: '{amount} imebaki',
      goalReached: 'Lengo limefikiwa',
      daysLeftLabel: 'siku {count}{suffix} zimebaki',
      targetDateReached: 'Tarehe ya lengo imefika',
      enableBrowserAlertsTitle: 'Washa arifa za kivinjari',
      enableBrowserAlertsBody: 'Washa arifa za kivinjari kwa tahadhari za kuzidi bajeti na miamala ya kurudia inayokaribia ukiwa na app wazi.',
      notificationsBlocked: 'Arifa zimezuiwa kwenye mipangilio ya kivinjari',
      enableAlerts: 'Washa arifa',
      notificationsEmpty: 'Uko sawa kwa sasa. Muhtasari wa wiki, tahadhari za kuzidi bajeti, na miamala ya kurudia itaonekana hapa.',
      timeLast7Days: 'Siku 7 zilizopita',
      timeCurrentCycle: 'Mzunguko wa sasa',
      timeAllTime: 'Muda wote',
      allCategories: 'Category zote',
      editHint: 'Tumia Hariri kufanya mabadiliko ya haraka, au bonyeza mara mbili kwenye row kama unapendelea.',
      noTransactionsMatch: 'Hakuna miamala inayolingana na mwonekano huu wa dashboard bado.',
      edit: 'Hariri',
      editing: 'Inahaririwa',
      delete: 'Futa',
      deleting: 'Inafuta...',
      transferIn: 'Uhamisho umeingia',
      transferOut: 'Uhamisho umetoka',
      editingSelectedTransaction: 'Unahariri muamala uliochaguliwa',
      saveChanges: 'Hifadhi mabadiliko',
      saving: 'Inahifadhi...',
      amountPlaceholder: 'Kiasi',
      categoryPlaceholder: 'Category',
      merchantPlaceholder: 'Merchant',
      notePlaceholder: 'Maelezo',
      transactionUpdated: 'Muamala umesasishwa',
      transactionDeleted: 'Muamala umefutwa',
      saveTransactionError: 'Weka kiasi sahihi kabla ya kuhifadhi.',
      updateTransactionError: 'Imeshindikana kusasisha muamala huu.',
      deleteTransactionConfirm: 'Ufute muamala huu kutoka kwenye orodha ya dashboard?',
      deleteTransactionError: 'Imeshindikana kufuta muamala huu.',
      browserAlertsEnabled: 'Arifa za kivinjari zimewashwa',
      monthlyOverspendWarning: 'Tahadhari ya kuzidi bajeti ya mwezi',
      monthlyOverspendBody: 'Kwa mwendo huu, unaelekea kuzidi bajeti ya mzunguko kwa {amount}.',
      categoryCloseTitle: '{category} inakaribia kiwango',
      categoryOverBody: 'Tayari umezidi kiwango cha {category} kwa {amount}.',
      categoryRemainingBody: '{amount} imebaki kwenye {category} katika mzunguko huu.',
      upcomingRecurringTitle: 'Muamala wa kurudia wa {type} unakaribia',
      upcomingRecurringBody: '{category} inadaiwa baada ya siku {days}{suffix} tarehe {date}.',
      weeklySummaryNotificationBody: 'Siku 7 zilizopita: umetumia {spent}. Matumizi salama ya kila siku kwa mzunguko uliobaki ni {safe}.',
    },
    settings: {
      preferences: 'Mapendeleo',
      settingsTitle: 'Mipangilio',
      appearance: 'Mwonekano',
      appearanceSubtitle: 'Chagua jinsi programu ya wavuti itaonekana. Chaguo lako litahifadhiwa kwenye kifaa hiki.',
      lightMode: 'Mwanga',
      darkMode: 'Giza',
      toggleTo: 'Badili kwenda',
      languageAndHelp: 'Lugha na msaada',
      languageSubtitle: 'Chagua lugha ya kutumia kwenye programu na fungua mwongozo wa haraka unapohitaji ukumbusho.',
      appLanguage: 'Lugha ya programu',
      openQuickGuides: 'Fungua mwongozo wa haraka',
      quickGuidesSubtitle: 'Jifunze mambo ya msingi, uhamisho, miamala ya kurudia, na vidokezo vya mzunguko wa bajeti sehemu moja.',
      budgetTargets: 'Malengo ya bajeti',
      account: 'Akaunti',
      signedInAs: 'Umeingia kama',
      signOut: 'Toka',
      confirmSignOut: 'Thibitisha kutoka',
      alertsAndReminders: 'Arifa na vikumbusho',
      alertsSubtitle: 'Chagua arifa unazotaka kuona. Web app iliyowekwa kwenye simu au desktop hufanya arifa hizi zifanye kazi vizuri zaidi.',
      browserInstalledAlerts: 'Arifa za kivinjari au app iliyowekwa',
      browserAlertsEnabledBody: 'Zimewashwa kwenye kivinjari hiki. Budget It inaweza kuleta vikumbusho wakati app inapatikana.',
      browserAlertsDisabledBody: 'Washa hili ili kuruhusu vikumbusho kwenye kivinjari au web app yako iliyowekwa.',
      browserAlertsUnsupportedBody: 'Kivinjari hiki hakina notification API, kwa hiyo arifa zitabaki ndani ya app.',
      overspendWarnings: 'Tahadhari za kuzidi bajeti na category',
      overspendWarningsBody: 'Pata tahadhari kasi ya matumizi au category zinazofuatiliwa zikianza kuondoka kwenye mstari.',
      recurringReminders: 'Vikumbusho vya miamala ya kurudia',
      recurringRemindersBody: 'Onyesha vikumbusho wakati kodi, subscription, mshahara, au miamala mingine ya kurudia inakaribia.',
      weeklySummaryUpdates: 'Masasisho ya muhtasari wa wiki',
      weeklySummaryUpdatesBody: 'Weka muhtasari wa matumizi wa kila wiki kwenye dashboard na uruhusu uonekane kwenye arifa.',
      on: 'Washa',
      off: 'Zima',
      allowBrowserNotifications: 'Ruhusu arifa za kivinjari',
      phoneFriendlyTip: 'Kidokezo cha simu',
      phoneFriendlyTipBody: 'Ukiongeza Budget It kwenye home screen, prompt za arifa na popup za vikumbusho huhisi zaidi kama app halisi kuliko kutumia tab ya kivinjari.',
    },
    guides: {
      eyebrow: 'Mwongozo wa Haraka',
      title: 'Jinsi ya kutumia Budget It',
      subtitle:
        'Maelezo mafupi ya sehemu muhimu zaidi za programu ili usipoteze muda unapohitaji msaada wa haraka.',
      cardGettingStarted: 'Kuanza',
      cardGettingStartedBody:
        'Weka lengo la kila siku, lengo la kila mwezi, sarafu, na siku ya kuanza mzunguko kwenye Mipangilio kwanza. Kisha ongeza muamala wako wa kwanza kutoka dashboard.',
      cardTransfers: 'Kuhamisha fedha',
      cardTransfersBody:
        'Tumia Hamisha fedha pale pesa zinapotoka kwenye benki kwenda kwenye envelope au kurudi. Uhamisho hubadilisha salio bila kuhesabika kama matumizi.',
      cardRecurring: 'Miamala ya kurudia',
      cardRecurringBody:
        'Tumia miamala ya kurudia kwa mshahara, kodi, subscription, na bili. Eneo la tahadhari kwenye dashboard litaonyesha kinachokaribia.',
      cardInsights: 'Taarifa na mipaka',
      cardInsightsBody:
        'Mipaka ya category huleta tahadhari, huku dashboard na analytics zikilinganisha kasi ya matumizi yako dhidi ya mzunguko wa sasa wa bajeti.',
      cardTags: 'Wafanyabiashara na tagi',
      cardTagsBody:
        'Ongeza merchant na tagi chache unapoweka muamala. Hii husaidia programu kutoa mapendekezo bora na kufanya taarifa za baadaye ziwe na maana zaidi.',
      tipTitle: 'Kidokezo',
      tipBody:
        'Ikiwa bajeti yako inaanza siku nyingine tofauti na tarehe 1, badilisha siku ya kuanza mzunguko kwenye Mipangilio ili takwimu zote zifuate ratiba yako halisi.',
      needAnythingElse: 'Unahitaji kitu kingine?',
      needAnythingElseBody:
        'Unaweza kurudi hapa wakati wowote kupitia kitufe cha alama ya swali kwenye juu ya ukurasa au kadi ya Lugha na msaada ndani ya Mipangilio.',
    },
    mobile: {
      nav: { dashboard: 'Dashibodi', add: 'Ongeza', history: 'Historia', insights: 'Taarifa', settings: 'Mipangilio' },
      dashboard: {
        loading: 'Inapakia dashibodi ya fedha zako...',
        loadError: 'Bajeti yako haikuweza kupakiwa',
        setupTitle: 'Andaa sehemu yako ya fedha',
        setupBody: 'Hatua tatu fupi zinaipa Budget It maelezo ya kukusaidia kusimamia matumizi yako.',
        setupStepOne: 'Weka malengo ya kila siku na kila mwezi',
        setupStepTwo: 'Chagua sarafu na siku ya kuanza mzunguko',
        setupStepThree: 'Ongeza matumizi yako ya kwanza baada ya kuandaa bajeti',
        openSetup: 'Anza kuandaa',
        tryAgain: 'Jaribu tena',
        offline: 'Huna mtandao. Unaona bajeti iliyohifadhiwa mwisho.',
        title: 'Mapigo ya bajeti yako',
        overPace: 'Kwa mwendo huu, unaweza kuzidi kwa {amount}.',
        underPace: 'Uko chini ya lengo kwa {amount}.',
        syncing: 'Inasawazisha bajeti yako', syncPulse: 'Mapigo ya usawazishaji', refreshing: 'Inasasisha data', updatedAt: 'Imesasishwa {time}', tapToRefresh: 'Gusa kusasisha',
        available: 'Inayopatikana', safeToday: 'Salama leo', addExpense: 'Ongeza matumizi', logIncome: 'Weka mapato', moveMoney: 'Hamisha fedha',
        today: 'Leo', cycle: 'Mzunguko', dailyTarget: '{percent}% ya lengo la siku', currentCycle: 'Mzunguko wa sasa',
        insights: 'Taarifa', stayOnTrack: 'Endelea kwenye mstari', slowPace: 'Punguza kasi kidogo', roomToBreathe: 'Bado una nafasi',
        safeSpend: 'Tumia karibu na {amount} kwa siku kwa siku {days} zijazo ili umalize mzunguko vizuri.',
        categoryWatch: 'Ufuatiliaji wa makundi', trackedLimits: 'Mipaka inayofuatiliwa', manage: 'Simamia',
        categoryHint: 'Ongeza mipaka ya makundi kwenye Mipangilio ili kuona maendeleo na tahadhari mapema hapa.',
        over: 'Imezidi', almostThere: 'Inakaribia', onTrack: 'Ipo sawa', spentOfLeft: '{spent} kati ya {limit} - {remaining} imebaki',
        recentActivity: 'Shughuli za hivi karibuni', latestTransactions: 'Miamala ya mwisho', viewAll: 'Tazama yote', noTransactions: 'Hakuna miamala bado. Ongeza mmoja ili dashibodi ianze kuonyesha picha kamili.',
      },
      transactions: {
        loading: 'Inapakia miamala...', offline: 'Huna mtandao: unaona miamala iliyohifadhiwa mwisho.', eyebrow: 'Njia ya fedha', title: 'Miamala',
        subtitle: 'Kagua matumizi, mapato, uhamisho, wafanyabiashara, na maelezo katika orodha moja safi.', expenses: 'Matumizi', incomeEntries: 'Mapato', transfers: 'Uhamisho',
        searchPlaceholder: 'Tafuta mfanyabiashara, kundi, maelezo, au tagi', allTime: 'Muda wote', lastSevenDays: 'Siku 7 zilizopita', thisMonth: 'Mwezi huu', all: 'Yote', income: 'Mapato',
        noResults: 'Hakuna miamala inayolingana na vichujio hivi.', noResultsBody: 'Jaribu kuondoa kichujio au kutafuta kitu kingine.', loadError: 'Miamala haikuweza kupakiwa', empty: 'Hakuna miamala bado',
        emptyBody: 'Ongeza matumizi au mapato yako ya kwanza na yataonekana hapa pamoja na mfanyabiashara na tagi.', retry: 'Jaribu tena', recurring: 'Inajirudia', actions: 'Vitendo vya muamala', deleteBody: 'Hii itafuta muamala na kusasisha salio.', deleteFailed: 'Muamala haukuweza kufutwa. Jaribu tena.', edit: 'Hariri', delete: 'Futa', cancel: 'Ghairi', transfer: 'Uhamisho',
      },
      transactionForm: {
        budgetFirst: 'Anza na bajeti', budgetFirstBody: 'Weka malengo yako kwenye Mipangilio, kisha rudi kuweka matumizi.', eyebrow: 'Weka haraka', title: 'Ongeza muamala wa fedha',
        subtitle: 'Weka kiasi, mfanyabiashara, tagi, na kundi kabla ya kusahau maelezo.', type: 'Aina', expense: 'Matumizi', income: 'Mapato', moneySpace: 'Sehemu ya fedha',
        moneySpaceHint: 'Chagua mahali muamala huu unapaswa kurekodiwa.', bankBalance: 'Salio la benki', available: 'inapatikana', amount: 'Kiasi', category: 'Kundi', details: 'Maelezo',
        merchantPlaceholder: 'Mfanyabiashara, mtu, au chanzo', recentMerchants: 'Wafanyabiashara wa karibuni', tagsPlaceholder: 'Tagi zikitengezwa kwa koma', datePlaceholder: 'YYYY-MM-DD', notePlaceholder: 'Ongeza maelezo...',
        saveExpense: 'Hifadhi matumizi', saveIncome: 'Hifadhi mapato', saving: 'Inahifadhi...', amountNeeded: 'Kiasi kinahitajika', validAmount: 'Tafadhali weka kiasi sahihi.',
        budgetNotReady: 'Bajeti haijawa tayari', setupBudget: 'Tafadhali andaa bajeti yako kwanza.', saved: 'Imehifadhiwa', incomeLogged: 'Mapato yamewekwa.', expenseAdded: 'Matumizi yameongezwa.',
        savedOffline: 'Imehifadhiwa kwenye simu hii. Itasawazishwa kiotomatiki mtandao ukirudi.', saveFailed: 'Haikuweza kuhifadhiwa',
      },
    },
  },
} as const satisfies Record<AppLanguage, TranslationTree>;

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set) => ({
      language: 'en',
      setLanguage: (language) => set({ language }),
    }),
    {
      name: 'budget-it-language',
      storage: languageStorage,
    }
  )
);

const getNestedTranslation = (tree: TranslationTree, path: string): string | undefined => {
  const value = path.split('.').reduce<TranslationLeaf | TranslationTree | undefined>((acc, key) => {
    if (!acc || typeof acc === 'string') return undefined;
    return acc[key];
  }, tree);

  return typeof value === 'string' ? value : undefined;
};

export const translate = (language: AppLanguage, key: string, fallback?: string) =>
  getNestedTranslation(translations[language], key) ||
  getNestedTranslation(translations.en, key) ||
  fallback ||
  key;

const formatTemplate = (template: string, values?: TemplateValues) => {
  if (!values) return template;
  return Object.entries(values).reduce(
    (output, [key, value]) => output.split(`{${key}}`).join(String(value)),
    template
  );
};

export const useI18n = () => {
  const language = useLanguageStore((state) => state.language);
  return {
    language,
    t: (key: string, fallback?: string) => translate(language, key, fallback),
    tr: (key: string, values?: TemplateValues, fallback?: string) =>
      formatTemplate(translate(language, key, fallback), values),
  };
};
